apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-delivery-pv 
  namespace: delivery
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/mongo-data"