apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: goodfood
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: traefik
    namespace: traefik
    port: 80
    localPort: 8080
    address: 0.0.0.0
profiles:
  # Profil pour créer les namespaces
  - name: namespace
    manifests:
      kustomize:
        paths:
          - ./Kafka/namespace
          - ./Traefik/namespace
  # Profil pour les CRDs et RBAC (Kafka et Traefik)
  - name: crds
    manifests:
      kustomize:
        paths:
          - ./Traefik/crds
          - ./Kafka/crds
  # Profil pour déployer uniquement Kafka
  - name: kafka
    manifests:
      kustomize:
        paths:
          - ./Kafka/resources
  # Profil pour déployer uniquement Traefik
  - name: traefik
    manifests:
      kustomize:
        paths:
          - ./Traefik/resources
  # Profil pour déployer uniquement Access Service
  - name: access-service
    build:
      artifacts:
        - image: access-service
          context: ../GoodFoodAccess
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-access

  # Profil pour l'application restaurateur
  - name: restaurateur
    build:
      artifacts:
        - image: goodfoodrestaurateur
          context: ../GoodFoodRestaurateur
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-restaurateur
  # Profil pour l'application client
  - name: client
    build:
      artifacts:
        - image: goodfoodclient
          context: ../GoodFoodClient
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-client
  # Profil pour l'application order
  - name: order
    build:
      artifacts:
        - image: goodfoodorder
          context: ../GoodFoodOrder
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-order
  # Profil pour client et order
  - name: client-order
    build:
      artifacts:
        - image: goodfoodclient
          context: ../GoodFoodClient
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
        - image: goodfoodorder
          context: ../GoodFoodOrder
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-client
          - ./Pod-order
  # Profil pour client et restaurateur
  - name: client-restaurateur
    build:
      artifacts:
        - image: goodfoodclient
          context: ../GoodFoodClient
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
        - image: goodfoodrestaurateur
          context: ../GoodFoodRestaurateur
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-client
          - ./Pod-restaurateur
  # Profil pour client, restaurateur et order
  - name: client-restaurateur-order
    build:
      artifacts:
        - image: goodfoodclient
          context: ../GoodFoodClient
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
        - image: goodfoodrestaurateur
          context: ../GoodFoodRestaurateur
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
        - image: goodfoodorder
          context: ../GoodFoodOrder
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-client
          - ./Pod-restaurateur
          - ./Pod-order
  # Profil pour tout déployer
  - name: all
    build:
      artifacts:
        - image: goodfoodrestaurateur
          context: ../GoodFoodRestaurateur
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
        - image: goodfoodclient
          context: ../GoodFoodClient
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
        - image: goodfoodorder
          context: ../GoodFoodOrder
          sync:
            manual:
              - src: "src/**/*.{js,ts}"
                dest: .
              - src: "package.json"
                dest: .
              - src: "tsconfig.json"
                dest: .
              - src: "*.{json,js,ts}"
                dest: .
          docker:
            target: dev
    manifests:
      kustomize:
        paths:
          - ./Pod-restaurateur
          - ./Pod-client
          - ./Pod-order