apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-restaurateur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-restaurateur
  template:
    metadata:
      labels:
        app: pod-restaurateur
    spec:
      containers:
        - name: restaurateur-db-container
          image: postgres:15
          imagePullPolicy: Always
          ports:
            - containerPort: 5434
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "postgres"
            - name: PGPORT
              value: "5434"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage

        - name: restaurateur-api-container
          image: goodfoodrestaurateur  # Image gérée par Skaffold
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "development"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5434"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "postgres"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        - name: restaurateur-web-container
          image: goodfoodwebrestaurateur  # Image gérée par Skaffold
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost:8080/restaurateur/api"
            - name: NEXT_PUBLIC_BASE_PATH
              value: "/restaurateur"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc