apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: restaurateur-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    # Route pour l'API (/restaurant/api/...)
    - match: Host(`localhost`) && PathPrefix(`/restaurant/api`)
      kind: Rule
      priority: 12
      services:
        - name: restaurateur-service
          namespace: default
          port: 3002
      middlewares:
        - name: strip-restaurant-api-prefix
          namespace: default

     # Route pour les fichiers statiques de Next.js (/_next/...)
    - match: Host(`localhost`) && PathPrefix(`/_next`)
      kind: Rule
      priority: 15
      services:
        - name: restaurateur-service
          namespace: default
          port: 4002
      middlewares: []

    # Route pour les autres chemins de l'application Next.js (avec suppression du préfixe /restaurant)
    - match: Host(`localhost`) && PathPrefix(`/restaurant`)
      kind: Rule
      priority: 10
      services:
        - name: restaurateur-service
          namespace: default
          port: 4002
      middlewares:
        - name: strip-restaurant-prefix
          namespace: default


---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-restaurant-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /restaurant

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-restaurant-api-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /restaurant/api