apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurateur-uploads-pvc
  namespace: restaurateur 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi 