apiVersion: v1
kind: PersistentVolume
metadata:
  name: restaurateur-uploads-pv
  namespace: restaurateur 
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/restaurant-uploads"
  persistentVolumeReclaimPolicy: Retain 