apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: restaurateur-public
  namespace: restaurateur
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/restaurateur/api`)
      kind: Rule
      priority: 12
      services:
        - name: restaurateur-service
          namespace: restaurateur
          port: 3002
      middlewares:
        - name: strip-restaurateur-api-prefix
          namespace: restaurateur
    - match: PathPrefix(`/restaurateur/api/uploads`)
      kind: Rule
      services:
        - name: restaurateur-service
          namespace: restaurateur
          port: 3002
      middlewares:
        - name: strip-restaurateur-api-prefix
          namespace: restaurateur

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: restaurateur-interservice
  namespace: restaurateur
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/restaurateur/api/restaurant/interservice`)
      kind: Rule
      priority: 13
      services:
        - name: restaurateur-service
          namespace: restaurateur
          port: 3002
      middlewares:
        - name: strip-restaurateur-api-prefix
          namespace: restaurateur
        - name: access-middleware
          namespace: access
    - match: PathPrefix(`/restaurateur/api/menu-items/interservice`)
      kind: Rule
      priority: 13
      services:
        - name: restaurateur-service
          namespace: restaurateur
          port: 3002
      middlewares:
        - name: strip-restaurateur-api-prefix
          namespace: restaurateur
        - name: access-middleware
          namespace: access
    - match: PathPrefix(`/restaurateur/api/menu-item-option-values/interservice`)
      kind: Rule
      priority: 13
      services:
        - name: restaurateur-service
          namespace: restaurateur
          port: 3002
      middlewares:
        - name: strip-restaurateur-api-prefix
          namespace: restaurateur
        - name: access-middleware
          namespace: access

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-restaurateur-api-prefix
  namespace: restaurateur
spec:
  stripPrefix:
    prefixes:
      - /restaurateur/api