apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: restaurateur-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    # Route pour l'API (/restaurateur/api/...)
    - match: Host(`localhost`) && PathPrefix(`/restaurateur/api`)
      kind: Rule
      priority: 12
      services:
        - name: restaurateur-service
          namespace: default
          port: 3002
      middlewares:
        - name: strip-restaurateur-api-prefix
          namespace: default

    # Route pour les autres chemins de l'application Next.js
    - match: Host(`localhost`) && PathPrefix(`/restaurateur`)
      kind: Rule
      priority: 10
      services:
        - name: restaurateur-service
          namespace: default
          port: 4002

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-restaurateur-api-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /restaurateur/api