apiVersion: v1
kind: Service
metadata:
  name: my-kafka-cluster-kafka-bootstrap
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka
    strimzi.io/cluster: my-kafka-cluster
spec:
  ports:
    - name: tcp-9092
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    strimzi.io/cluster: my-kafka-cluster
    app.kubernetes.io/name: kafka
  type: ClusterIP