apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
  - strimzi-cluster.yaml
  - kafka-cluster.yaml
  - kafka-ui-deployment.yaml
  - topics/kafka-topic-orders.yaml