apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: client-orders
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000 # 7 jours