apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: order
resources:
  - order-namespace.yaml
  - order-pv.yaml
  - order-pvc.yaml
  - order-deployment.yaml 
  - order-service.yaml
  - order-ingressroute.yaml