# order/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-order
  namespace: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-order
  template:
    metadata:
      labels:
        app: pod-order
    spec:
      containers:
        - name: order-db-container
          image: postgres:15
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5437
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "k?:u-Nu4&FM68Q!1Ez"
            - name: POSTGRES_DB
              value: "goodfood_order"
            - name: PGPORT
              value: "5437"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: order-storage
        - name: order-api-container
          image: goodfoodorder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              value: "development"
            - name: APP_PORT
              value: "3005"
            - name: BACKEND_DOMAIN
              value: "http://localhost:8080/order/api"
            - name: DATABASE_TYPE
              value: "postgres"
            - name: DATABASE_HOST
              value: "127.0.0.1"
            - name: DATABASE_PORT
              value: "5437"
            - name: DATABASE_USERNAME
              value: "user"
            - name: DATABASE_PASSWORD
              value: "k?:u-Nu4&FM68Q!1Ez"
            - name: DATABASE_NAME
              value: "goodfood_order"
            - name: DATABASE_SYNCHRONIZE
              value: "true"
            - name: DATABASE_URL
              value: "postgres://user:k?:u-Nu4&FM68Q!1Ez@127.0.0.1:5437/goodfood_order"
            - name: AUTH_JWT_SECRET
              value: "3v8g7h6J9LkM0pQ2XrTzWmYbNcDfGqRt"
            - name: AUTH_JWT_TOKEN_EXPIRES_IN
              value: "1h"
            - name: AUTH_REFRESH_SECRET
              value: "A9B8C7D6E5F4G3H2I1J0KLMNOPQRSTU"
            - name: AUTH_REFRESH_TOKEN_EXPIRES_IN
              value: "10h"
            - name: MAILER_HOST
              value: "smtp.gmail.com"
            - name: MAILER_PORT
              value: "587"
            - name: MAILER_USER
              value: "goodfood.maalsi@gmail.com"
            - name: MAILER_PASSWORD
              value: "rwpe gfjy gwmj btyt"
            - name: MAILER_IGNORE_TLS
              value: "false"
            - name: MAILER_SECURE
              value: "false"
            - name: MAILER_REQUIRE_TLS
              value: "true"
            - name: MAILER_DEFAULT_EMAIL
              value: "goodfood.maalsi@gmail.com"
            - name: MAILER_DEFAULT_NAME
              value: "Goodfood"
            - name: MAILER_CLIENT_PORT
              value: "1080"
            - name: KAFKAJS_NO_PARTITIONER_WARNING
              value: "1"
            - name: RUN_SEEDERS
              value: "true"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: client_secret
            - name: RESTAURATEUR_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: restaurateur_secret
            - name: DELIVERY_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: delivery_secret
            - name: CLIENT_SERVICE_URL
              value: "http://traefik.traefik.svc.cluster.local:80/client/api"
            - name: RESTAURANT_SERVICE_URL
              value: "http://traefik.traefik.svc.cluster.local:80/restaurateur/api"
            - name: DELIVERY_SERVICE_URL
              value: "http://traefik.traefik.svc.cluster.local:80/delivery/api"
            - name: MENU_ITEM_OPTION_VALUE_URL
              value: "http://traefik.traefik.svc.cluster.local:80/restaurateur/api"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
      volumes:
        - name: order-storage
          persistentVolumeClaim:
            claimName: order-pvc