apiVersion: v1
kind: PersistentVolume
metadata:
  name: administrateur-pv
  namespace: administrateur
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"