apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-service
  namespace: access
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-service
  template:
    metadata:
      labels:
        app: access-service
    spec:
      containers:
        - name: access-service
          image: access-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: client_secret
            - name: RESTAURATEUR_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: restaurateur_secret
            - name: DELIVERY_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: delivery_secret
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"