# access/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: access
type: Opaque
data:
  client_secret: M3Y4ZzdoNko5TGtNMHBRMlhyVHpXbVliTmNEZkdxUnQ=
  restaurateur_secret: M3Y4ZzdoNko5TGtNMHBRMlhyVHpXbVliTmNEZkdxUnQ=
  delivery_secret: M3Y4ZzdoNko5TGtNMHBRMlhyVHpXbVliTmNEZkdxUnQ=