apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: access
type: Opaque
data:
  client_secret: 3v8g7h6J9LkM0pQ2XrTzWmYbNcDfGqRt
  restaurateur_secret: 3v8g7h6J9LkM0pQ2XrTzWmYbNcDfGqRt
  livreur_secret: 3v8g7h6J9LkM0pQ2XrTzWmYbNcDfGqRt
  admin_secret: 3v8g7h6J9LkM0pQ2XrTzWmYbNcDfGqRt