apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: client-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    # Route pour l'API (/client/api/...)
    - match: Host(`localhost`) && PathPrefix(`/client/api`)
      kind: Rule
      priority: 12
      services:
        - name: client-service
          namespace: default
          port: 3001
      middlewares:
        - name: strip-client-api-prefix
          namespace: default

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-client-api-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /client/api